name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: UTBM-FISA-projects
      - uses: lowlighter/metrics@latest
        with:
          filename: projects.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_projects: yes
          plugin_projects_repositories: UTBM-FISA-projects/TerraGen-Front/TerraGen%20Kanban
          plugin_projects_descriptions: yes
      - uses: lowlighter/metrics@latest
        with:
          filename: languages.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_sections: recently-used
          plugin_languages_details: bytes-size, percentage
